= LIBRARY DESCRIPTION

Helper framework for basic opportunities(like guava, apache commons)

You can find the library in
https://mvnrepository.com/artifact/life.expert/himalaya[Maven Central]

Add library in Gradle:
[source,groovie]
dependencies {
    implementation 'life.expert:himalaya:1.0.51'
    }

== LIBRARY DEVELOPER NOTES


* Please install
https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html[*LATEST!* version java 12]

* Please install
https://docs.gradle.org/current/userguide/installation.html[latest version gradle 5.6]

* Simpliest way - is to use project's gradle wrapper (with smallest gradle-wrapper.jar inside for gradle downloading).
But some organizations (banks:) do not allow projects to submit binary files.
The alternative approach to install gradle and generate gradle wrapper
[source,bash]
gradle wrapper

* for building project use
https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/[gradle plugin]
[source,bash]
gradlew build





== ARCHITECTURE NOTES


=== INFORMATION SYSTEM ARCHITECTURE

* this application uses  https://github.com/wilmerkrisp/patterns/blob/master/patterns.pdf[patterns from the classifier]

* for installing the same environment set File--Settings repository = https://github.com/wilmerkrisp/idesettingrepository[git@github.com:wilmerkrisp/idesettingrepository.git] +
 and app template used  https://github.com/wilmerkrisp/apptemplate/tree/master/winter

* gradle used (see /build.gradle), please use gradle wrapper ./gradlew for running tasks
** project name inside settings.gradle (rootProject.name)
** main class name and version setted inside build.gradle

NOTE: IDE--Settings--Build--Gradle: +
select: Gradle wrapper customization in build script +
delegate IDE build/run actions to gradle

* project source sets:
** main
** test


* well-known libraries are widely used (Guava, Apache commons)
** in accordance with the principles of reference architectures of https://www.opengroup.org/togaf[TOGAF] architecture,

** Lombok annotations are widely used, see configuration inside build.gradle (then /lombok.config autogenerated)

** - slf4j used for logging (library client's logger implementation), logback used only for tests logs


* partially used functional approach (Vavr, Cyclops)
** wrapping checked exceptions into bool, Try, Either, flow events, Optional depending on situations
** pattern matching inside Switch
** so as the excitement of the exceptions is expensive then all errors are reported as events of the flow

* reactive approach is used (Spring Reactor) for further parallel scaling of threads

* the following https://github.com/wilmerkrisp/conventions[coding standards and conventions were used]

=== TECHNOLOGICAL ARCHITECTURE

* monitoring and outer recovery from failures outside the scope of this code



